__1.__ Найти скалярное произведение векторов $x, y \in \mathbb{R}$:<br>
а) $x=(0,-3, 6),~y=(-4, 7, 9);$<br>
б) $x=(7, -4, 0, 1),~y=(-3, 1, 11, 2).$


a) $(x,y) = 0\cdot(-4) + (-3)\cdot7 + 6\cdot9 = -21 + 54 = 33$

б) $(x,y) = 7\cdot(-3) + (-4)\cdot1 + 0\cdot11 + 1\cdot2 = -21 - 4 + 2 = -23$

In [4]:
import numpy as np
from numpy.linalg import norm

In [7]:
x1 = np.array([0, -3, 6])
y1 = np.array([-4, 7, 9])

In [8]:
x1 @ y1

33

In [9]:
x2 = np.array([7, -4, 0, 1])
y2 = np.array([-3, 1, 11, 2])

In [10]:
x2 @ y2

-23

__2.__ Найти нормы векторов $(4, 2, 4)$ и $(12, 3, 4)$ и угол между ними.


1. Манхэттенские нормы: $\left\|a\right\|_{1} = |4|+|2|+|4|=10$, $\left\|b\right\|_{1} = |12|+|3|+|4|=19$.
2. Евклидовы нормы: $\left\|a\right\|_{2} = \sqrt{4^{2}+2^{2}+4^{2}}=\sqrt{36}=6$, $\left\|a\right\|_{2} = \sqrt{12^{2}+3^{2}+4^{2}}=\sqrt{169}=13$.
3. Угол между векторами: $cos\varphi = \frac{4\cdot12+2\cdot3+4\cdot64}{\sqrt{4^{2}+2^{2}+4^{2}}\sqrt{12^{2}+3^{2}+4^{2}}}=\frac{70}{6\cdot13}=\frac{70}{78}\approx 0.897$

In [11]:
a = np.array([4, 2, 4])
b = np.array([12, 3, 4])

In [12]:
print(f'Манхэттенские нормы векторов a: {norm(a, ord=1)}, b: {norm(b, ord=1)}')

Манхэттенские нормы векторов a: 10.0, b: 19.0


In [14]:
norm_a = norm(a)
norm_b = norm(b)

print(f'Евклидовы нормы векторов a: {norm_a}, b: {norm_b}')

Евклидовы нормы векторов a: 6.0, b: 13.0


In [15]:
print(f'Угол между векторами a и b: {(a @ b) / (norm_a * norm_b)}')

Угол между векторами a и b: 0.8974358974358975


__3.__ Будет ли линейное пространство евклидовым, если за скалярное произведение принять:<br>
а) произведение длин векторов;<br>
б) утроенное обычное скалярное произведение векторов?<br>
      

а) для данного вида скалярного произведения не будет выполняться 3 аксиома: $(x_{1}+x_{2},y)=(x_{1},y)+(x_{2},y);$.
В левой части выражения получаем: $\left\|x_{1} + x_{2}\right\|\cdot\left\|y\right\|$, а в правой: $\left\|x_{1}\right\|\cdot\left\|y\right\| + \left\|x_{2}\right\|\cdot\left\|y\right\| = (\left\|x_{1}\right\| + \left\|x_{2}\right\|)\cdot\left\|y\right\|$.
Длина суммы двух векторов в общем случае не равна сумме длин векторов. Это равенство верно только в том случае, если вектора коллинеарны и направлены в одну сторону.

б) данный вид скалярного произведения будет удовлетворять всем условиям евклидова пространства, т.к. множитель "3" не влияет на выполнение аксиом (выносится во всех случаях, а обычное скалярное произведение уже удовлетворяет условиям).

__4.__ Какие из нижеперечисленных векторов образуют ортонормированный базис в линейном пространстве $\mathbb{R}^{3}$:<br>
а) $(1,0,0),(0,0,1);$ <br>
б) $(1/\sqrt{2},-1/\sqrt{2},0),(1/\sqrt{2},1/\sqrt{2},0), (0,0,1);$<br>
в) $(1/2, -1/2, 0), (0, 1/2, 1/2), (0,0,1);$<br>
г) $(1,0,0),(0,1,0),(0,0,1)?$ 


Для ортонормированного базиса должно выполняться условие $(e_{i}, e_{j})=0$ $\forall$ $i\neq j$ и $(e_{i},e_{i})=1$ $\forall$ $i\in[1, n].$

In [75]:
def check_ortonorm(basis):
    n = basis.shape[0]
    return np.array([[round(basis[i] @ basis[j], 6) for j in range(n)] for i in range(n)])

a) нет - в базисе должно быть 3 вектора, т.к. пространство $\mathbb{R}^{3}$.

In [80]:
x1 = np.array([1/np.sqrt(2),-1/np.sqrt(2),0])
x2 = np.array([1/np.sqrt(2),1/np.sqrt(2),0])
x3 = np.array([0,0,1])
check_ortonorm(np.vstack((x1, x2, x3)))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

б) да: вектора имеют единичную длину и попарно ортогональны.

In [77]:
x1 = np.array([1/2,-1/2,0])
x2 = np.array([0,1/2,1/2])
x3 = np.array([0,0,1])
check_ortonorm(np.vstack((x1, x2, x3)))

array([[ 0.5 , -0.25,  0.  ],
       [-0.25,  0.5 ,  0.5 ],
       [ 0.  ,  0.5 ,  1.  ]])

в) нет.

In [78]:
x1 = np.array([1,0,0])
x2 = np.array([0,1,0])
x3 = np.array([0,0,1])
check_ortonorm(np.vstack((x1, x2, x3)))

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

г) да: вектора имеют единичную длину и попарно ортогональны.