__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

In [1]:
import numpy as np
from scipy.linalg import det, lu_factor, lu_solve

__Решение__

а) $det(A) = 1\cdot(-4) - (-2)\cdot3 = 2$

$det(A_{1}) = 1\cdot(-4) - (-2)\cdot7 = 10$

$det(A_{2}) = 1\cdot7 - 1\cdot3 = 4$

$x_{1} = \frac{det(A_{1})}{det(A)} = \frac{10}{2} = 5$

$x_{2} = \frac{det(A_{2})}{det(A)} = \frac{4}{2} = 2$

In [2]:
def SoLE_by_Kramer(A, b):
    det_A = det(A)
    n = A.shape[0]
    x = np.array(np.zeros([n]))
    
    for i in range(n):
        A_mod = A.copy().T
        A_mod[i, :] = b
        x[i] = det(A_mod.T) / det_A
        
    return x

In [3]:
A = np.array([[1, -2], [3, -4]])
b = np.array([1, 7])
x = SoLE_by_Kramer(A, b)
print(f"Решение x: {x}")
print(f"проверка решения: {np.allclose(A @ x - b, np.zeros((A.shape[0],)))}")

Решение x: [5. 2.]
проверка решения: True


In [4]:
lu, piv = lu_factor(A)
x = lu_solve((lu, piv), b)
print(f"Решение с помощью scipy: {x}")
print(f"проверка решения: {np.allclose(A @ x - b, np.zeros((A.shape[0],)))}")

Решение с помощью scipy: [5. 2.]
проверка решения: True


б)

а) $det(A) = 2\cdot(1\cdot1 - (-3)\cdot4) - (-1)\cdot(1\cdot1 - (-3)\cdot2) + 5\cdot(1\cdot4 - 1\cdot2) = 43$

$det(A_{1}) = 10\cdot(1\cdot1 - (-3)\cdot4) - (-1)\cdot(-2\cdot1 - (-3)\cdot1) + 5\cdot(-2\cdot4 - 1\cdot1) = 86$

$det(A_{2}) = 2\cdot(-2\cdot1 - (-3)\cdot1) - 10\cdot(1\cdot1 - (-3)\cdot2) + 5\cdot(1\cdot1 - (-2)\cdot2) = -43$

$det(A_{3}) = 2\cdot(1\cdot1 - (-2)\cdot4) - (-1)\cdot(1\cdot1 - (-2)\cdot2) + 10\cdot(1\cdot4 - 1\cdot2) = 43$

$x_{1} = \frac{det(A_{1})}{det(A)} = \frac{86}{43} = 2$

$x_{2} = \frac{det(A_{2})}{det(A)} = \frac{-43}{43} = -1$

$x_{3} = \frac{det(A_{3})}{det(A)} = \frac{43}{43} = 1$

In [5]:
A = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
b = np.array([10, -2, 1])
x = SoLE_by_Kramer(A, b)
print(f"Решение x: {x}")
print(f"проверка решения: {np.allclose(A @ x - b, np.zeros((A.shape[0],)))}")

Решение x: [ 2. -1.  1.]
проверка решения: True


In [6]:
lu, piv = lu_factor(A)
x = lu_solve((lu, piv), b)
print(f"Решение с помощью scipy: {x}")
print(f"проверка решения: {np.allclose(A @ x - b, np.zeros((A.shape[0],)))}")

Решение с помощью scipy: [ 2. -1.  1.]
проверка решения: True


__5*.__ Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

In [7]:
def get_LU(A):
    LU = np.matrix(np.zeros([A.shape[0], A.shape[1]]))
    N = A.shape[0]

    for k in range(N):
        for j in range(k, N):
            LU[k, j] = A[k, j] - LU[k, :k] * LU[:k, j]
            
        for i in range(k + 1, N):
            LU[i, k] = (A[i, k] - LU[i, : k] * LU[: k, k]) / LU[k, k]

    return LU

In [8]:
def get_L(LU):
    L = LU.copy()
    for i in range(L.shape[0]):
            L[i, i] = 1
            L[i, i + 1 :] = 0
    return np.matrix(L)


def get_U(LU):
    U = LU.copy()
    for i in range(1, U.shape[0]):
        U[i, :i] = 0
    return U

In [9]:
def SoLE_by_LU(LU, b):
    n = LU.shape[0]
    y = np.matrix(np.zeros([n, 1]))
    for i in range(n):
        y[i, 0] = b[i, 0] - LU[i, :i] * y[:i]
    
    x = np.matrix(np.zeros([n, 1]))
    for i in range(1, n + 1):
        x[-i, 0] = (y[-i] - LU[-i, -i:] * x[-i:, 0] ) / LU[-i, -i]

    return x

__2*.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

__Решение__

а)

In [10]:
A = np.array([[1, 2, 4], [2, 9, 12], [3, 26, 30]])
print(f"Матрица А:\n{A}")
LU = get_LU(A)
print(f"Матрица LU:\n{LU}")
L = get_L(LU)
U = get_U(LU)
print(f"Матрица L:\n{L}")
print(f"Матрица U:\n{U}")
print(f"проверка LU-разложения: {np.allclose(A - L @ U, np.zeros((A.shape[0],)))}")
print("LU с помощью scipy: ")
lu_factor(A)

Матрица А:
[[ 1  2  4]
 [ 2  9 12]
 [ 3 26 30]]
Матрица LU:
[[1. 2. 4.]
 [2. 5. 4.]
 [3. 4. 2.]]
Матрица L:
[[1. 0. 0.]
 [2. 1. 0.]
 [3. 4. 1.]]
Матрица U:
[[1. 2. 4.]
 [0. 5. 4.]
 [0. 0. 2.]]
проверка LU-разложения: True
LU с помощью scipy: 


(array([[ 3.        , 26.        , 30.        ],
        [ 0.66666667, -8.33333333, -8.        ],
        [ 0.33333333,  0.8       ,  0.4       ]]),
 array([2, 1, 2], dtype=int32))

б)

In [11]:
A = np.array([[1, 1, 2, 4], [2, 5, 8, 9], [3, 18, 29, 18], [4, 22, 53, 33]])
print(f"Матрица А:\n{A}")
LU = get_LU(A)
print(f"Матрица LU:\n{LU}")
L = get_L(LU)
U = get_U(LU)
print(f"Матрица L:\n{L}")
print(f"Матрица U:\n{U}")
print(f"проверка LU-разложения: {np.allclose(A - L @ U, np.zeros((A.shape[0],)))}")
print("LU с помощью scipy: ")
lu_factor(A)

Матрица А:
[[ 1  1  2  4]
 [ 2  5  8  9]
 [ 3 18 29 18]
 [ 4 22 53 33]]
Матрица LU:
[[1. 1. 2. 4.]
 [2. 3. 4. 1.]
 [3. 5. 3. 1.]
 [4. 6. 7. 4.]]
Матрица L:
[[1. 0. 0. 0.]
 [2. 1. 0. 0.]
 [3. 5. 1. 0.]
 [4. 6. 7. 1.]]
Матрица U:
[[1. 1. 2. 4.]
 [0. 3. 4. 1.]
 [0. 0. 3. 1.]
 [0. 0. 0. 4.]]
проверка LU-разложения: True
LU с помощью scipy: 


(array([[  4.        ,  22.        ,  53.        ,  33.        ],
        [  0.5       ,  -6.        , -18.5       ,  -7.5       ],
        [  0.75      ,  -0.25      , -15.375     ,  -8.625     ],
        [  0.25      ,   0.75      ,  -0.17073171,  -0.09756098]]),
 array([3, 1, 2, 3], dtype=int32))

__3*.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

In [12]:
A = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
print(f"Матрица А:\n{A}")
LU = get_LU(A)
print(f"Матрица LU:\n{LU}")
L = get_L(LU)
U = get_U(LU)
print(f"Матрица L:\n{L}")
print(f"Матрица U:\n{U}")
print(f"проверка LU-разложения: {np.allclose(A - L @ U, np.zeros((A.shape[0],)))}")

b = np.array([[1], [-6], [-5]])
x = SoLE_by_LU(LU, b)

print(f"Решение x = {x}")
print(f"проверка решения: {np.allclose(A @ x - b, np.zeros((A.shape[0],)))}")

lu, piv = lu_factor(A)
x = lu_solve((lu, piv), b)
print(f"Решение с помощью scipy: {x}")
print(f"проверка решения: {np.allclose(A @ x - b, np.zeros((A.shape[0],)))}")

Матрица А:
[[ 2  1  3]
 [11  7  5]
 [ 9  8  4]]
Матрица LU:
[[  2.           1.           3.        ]
 [  5.5          1.5        -11.5       ]
 [  4.5          2.33333333  17.33333333]]
Матрица L:
[[1.         0.         0.        ]
 [5.5        1.         0.        ]
 [4.5        2.33333333 1.        ]]
Матрица U:
[[  2.           1.           3.        ]
 [  0.           1.5        -11.5       ]
 [  0.           0.          17.33333333]]
проверка LU-разложения: True
Решение x = [[-1.]
 [ 0.]
 [ 1.]]
проверка решения: True
Решение с помощью scipy: [[-1.]
 [ 0.]
 [ 1.]]
проверка решения: True


__4*.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

__Решение__

Разложение на $LL^{T}$:

$$l_{11} = \sqrt{a_{11}} = \sqrt{81} = 9,$$
$$l_{21} = \frac{a_{21}}{l_{11}} = \frac{-45}{9} = -5,$$
$$l_{31} = \frac{a_{31}}{l_{11}}=\frac{45}{9} = 5,$$

$$l_{22}=\sqrt{a_{22}-l_{21}^{2}} = \sqrt{50 - 25} = 5,$$
$$l_{32}=\frac{1}{l_{22}}\left ( a_{32}-l_{21}l_{31} \right) = \frac{1}{5}\left ( -15 - (-5)\cdot5 \right ) = 2,$$

$$l_{33}=\sqrt{a_{33}-l_{31}^{2}-l_{32}^{2}} = \sqrt{38 - 25 - 4} = 3.$$

Получили матрицу 

$$L = \begin{pmatrix}
9 & 0 & 0 \\ 
-5 & 5 & 0 \\ 
5 & 2 & 3
\end{pmatrix}, 
\; \; 
L^{T} = \begin{pmatrix}
9 & -5 & 5 \\ 
0 & 5 & 2 \\ 
0 & 0 & 3
\end{pmatrix}.$$

Решаем систему $Ly=b:$

$$\begin{cases}
9y_{1} = 531, \\
-5y_{1} + 5y_{2} = -460, \\
5y_{1} + 2y_{2} + 3y_{3} = 193.
\end{cases}$$

$$y_{1} = 59,$$

$$y_{2} = \frac{5\cdot 59 - 460}{5} = -33,$$

$$y_{3} = \frac{193 - 5\cdot59 - 2\cdot(-33)}{3} = -12.$$

И решаем систему $L^{T}x = y:$

$$\begin{cases}
9x_{1} - 5x_{2} + 5x_{3} = 59, \\
5x_{2} + 2x_{3} = -33, \\
3x_{3} = -12.
\end{cases}$$

$$x_{3} = -4,$$

$$x_{2} = \frac{-33 - 2\cdot(-4)}{5} = -5,$$

$$x_{1} = \frac{59 + 5\cdot(-5) - 5\cdot(-4)}{9} = 6.$$

Проверяем, подставляя полученные значения в исходную систему:

$$\begin{cases}
81\cdot6 - 45\cdot(-5) + 45\cdot(-4) = 531, \\
-45\cdot6 + 50\cdot(-5) - 15\cdot(-4) = -460, \\
45\cdot6 - 15\cdot(-5) + 38\cdot(-4) = 193.
\end{cases}$$

In [13]:
from scipy.linalg import cholesky, solve_triangular

In [14]:
A = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
b = np.array([531, -460, 193])
L = cholesky(A).T
print(f"Матрица L: \n{L}")
y = solve_triangular(L, b, lower = True, check_finite = False)
x = solve_triangular(L, y, lower = True, trans = 1, check_finite = False)
print(f"Решение х: {x}")

Матрица L: 
[[ 9.  0.  0.]
 [-5.  5.  0.]
 [ 5.  2.  3.]]
Решение х: [ 6. -5. -4.]
