__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.
    

а) произведения невозможны.

б) возможно произведение $AB$ с размерностью результата $2\times3$.

в) возможны произведения: $AB$ с размерностью результата $8\times8$ и $BA$ с размерностью результата $3\times3$.

г) возможны произведения: $AB$ $BA$ с одинаковой размерностью результата $4\times4$.

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$


Сумма: $A + B = \begin{pmatrix}
1+4 & -2-1\\ 
3+0 & 0+5
\end{pmatrix} = \begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$

Произведение: $AB = \begin{pmatrix}
1\cdot4 + -2\cdot0 & 1\cdot(-1) + -2\cdot5\\ 
3\cdot4 + 0\cdot0 & 3\cdot(-1) + 0\cdot5
\end{pmatrix} = \begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}$, $BA = \begin{pmatrix}
4\cdot1 + (-1)\cdot3 & 4\cdot(-2) + (-1)\cdot0\\ 
0\cdot1 + 5\cdot3 & 0\cdot(-2) + 5\cdot0
\end{pmatrix} = \begin{pmatrix}
1 & -8\\ 
15 & 0
\end{pmatrix}$

In [2]:
import numpy as np

In [8]:
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])
print(f'A:{a}\nB:{b}')

A:[[ 1 -2]
 [ 3  0]]
B:[[ 4 -1]
 [ 0  5]]


In [9]:
a+b

array([[ 5, -3],
       [ 3,  5]])

In [10]:
print(f'AB:{a@b}\nBA:{b@a}')

AB:[[  4 -11]
 [ 12  -3]]
BA:[[ 1 -8]
 [15  0]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$
    

$3A-2B+4C = \begin{pmatrix}
3\cdot1 - 2\cdot0 + 4\cdot2 & 3\cdot7 - 2\cdot5 + 4\cdot(-4)\\ 
3\cdot3 - 2\cdot2 + 4\cdot1 & 3\cdot(-6) - 2\cdot(-1) + 4\cdot1
\end{pmatrix} = \begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$

In [11]:
a = np.array([[1, 7], [3, -6]])
b = np.array([[0, 5], [2, -1]])
c = np.array([[2, -4], [1, 1]])
print(f'A:{a}\nB:{b}\nC:{c}')

A:[[ 1  7]
 [ 3 -6]]
B:[[ 0  5]
 [ 2 -1]]
C:[[ 2 -4]
 [ 1  1]]


In [12]:
3*a - 2*b + 4*c

array([[ 11,  -5],
       [  9, -12]])

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.


$A^{T} = \begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}$

$AA^{T} = \begin{pmatrix}
4\cdot4 + 1\cdot1 & 4\cdot5 + 1\cdot(-2) & 4\cdot2 + 1\cdot3\\ 
5\cdot4 + (-2)\cdot1 & 5\cdot5 + (-2)\cdot(-2) & 5\cdot2 + (-2)\cdot3\\ 
2\cdot4 + 3\cdot1 & 2\cdot5 + 3\cdot(-2) & 2\cdot2 + 3\cdot3
\end{pmatrix} = \begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\ 
11 & 4 & 13
\end{pmatrix}$

$A^{T}A = \begin{pmatrix}
4\cdot4 + 5\cdot5 + 2\cdot2 & 4\cdot1 + 5\cdot(-2) + 2\cdot3\\ 
1\cdot4 + (-2)\cdot5 + 3\cdot2 & 1\cdot1 + (-2)\cdot(-2) + 3\cdot3
\end{pmatrix} = \begin{pmatrix}
45 & 0\\ 
0 & 14
\end{pmatrix}$

In [13]:
a = np.array([[4, 1], [5, -2], [2, 3]])
print(f'A:{a}')

A:[[ 4  1]
 [ 5 -2]
 [ 2  3]]


In [16]:
a_T = a.T
a_T

array([[ 4,  5,  2],
       [ 1, -2,  3]])

In [17]:
a@a_T

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [18]:
a_T@a

array([[45,  0],
       [ 0, 14]])

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [53]:
def matrix_mul(a, b):
    dim1 = len(a)
    dim2 = len(a[0])
    dim_check = len(b)
    dim3 = len(b[0])
    if dim2 != dim_check:
        return f"Матрицы нельзя перемножить, т.к. вторая размерность {dim2} первой матрицы не равна первой размерности {dim_check} второй матрицы"
    
    return [[sum([a[i][j]*b[j][k] for j in range(dim2)]) for k in range(dim3)] for i in range(dim1)]

In [54]:
a = [[1, 2, 2, 3], [5, -3, 4, 2], [2, -1, 0, -9]]
b = [[10, -2, 5, 4, 2, 3], [1, 0, -22, 6, 1, 0], [0, 8, 7, 3, 2, 0], [3, 10, 0, -8, 4, 5]]
c = [[3, 2], [5, 3]]

In [55]:
matrix_mul(a, b)

[[21, 44, -25, -2, 20, 18],
 [53, 42, 119, -2, 23, 25],
 [-8, -94, 32, 74, -33, -39]]

In [56]:
np_a = np.array(a)
np_b = np.array(b)
np_a @ np_b

array([[ 21,  44, -25,  -2,  20,  18],
       [ 53,  42, 119,  -2,  23,  25],
       [ -8, -94,  32,  74, -33, -39]])

In [57]:
matrix_mul(a, c)

'Матрицы нельзя перемножить, т.к. вторая размерность 4 первой матрицы не равна первой размерности 2 второй матрицы'

In [58]:
np_c = np.array(c)
np_a @ np_c

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 4)