__1.__ Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

**Решение.**

Составляем и решаем характеристическое уравнение для поиска собственных значений:

$$\begin{vmatrix}
-1 - \lambda & -6\\ 
2 & 6 - \lambda
\end{vmatrix} = 0,$$

$$(-1 - \lambda)(6 - \lambda) - (-6)\cdot2 = 0,$$

$$\lambda^{2} + \lambda - 6\lambda - 6 + 12 = 0,$$

$$\lambda^{2} - 5\lambda + 6 = 0,$$

$$(\lambda - 2)(\lambda - 3) = 0,$$

$$\lambda_{1} = 2,\,\lambda_{2} = 3.$$

Находим собственные векторы вида $\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}$ для каждого собственного значения, решив выражение $\textbf{A}x=\lambda x$:

$$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
\lambda_{1}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix},\,\,\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
\lambda_{2}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}.
$$

Получаем

$$\begin{cases}
-x_{1} - 6\cdot x_{2}= 2\cdot x_{1}, \\
2\cdot x_{1} + 6\cdot x_{2}= 2\cdot x_{2}.
\end{cases},\,\,\, \begin{cases}
-x_{1} - 6\cdot x_{2}= 3\cdot x_{1}, \\
2\cdot x_{1} + 6\cdot x_{2}= 3\cdot x_{2}.
\end{cases}$$ 

Перенеся всё в левую часть, получим:

$$\begin{cases}
-3\cdot x_{1} - 6\cdot x_{2}= 0, \\
2\cdot x_{1} + 4\cdot x_{2}= 0.
\end{cases},\,\,\, \begin{cases}
-4\cdot x_{1} - 6\cdot x_{2}= 0, \\
2\cdot x_{1} + 3\cdot x_{2}= 0.
\end{cases}$$ 

Видно, что для $\lambda_{1}: x_{1} = -2\cdot x_{2}$, а для $\lambda_{2}: x_{1} = -\frac{3}{2}\cdot x_{2}$. Следовательно, можно взять любые два вектора, координаты которых отвечают этим условиям, а затем нормировать каждый. Найдём нормы для векторов, используя отношения между координатами и взяв $x_{2} > 0$ (для упрощения вычислений):

$$\sqrt{x_{1}^{2} + x_{2}^{2}} = \sqrt{(-2\cdot x_{2})^{2} + x_{2}^{2}} = \sqrt{5}\cdot x_{2}$$

$$\sqrt{x_{1}^{2} + x_{2}^{2}} = \sqrt{(-\frac{3}{2}\cdot x_{2})^{2} + x_{2}^{2}} = \frac{\sqrt{13}}{2}\cdot x_{2}$$

И получаем собственные вектора, нормируя координаты:

для $\lambda_{1} = 2$
$$\begin{pmatrix}
\frac{x_{1}}{\sqrt{5}\cdot x_{2}}\\ 
\frac{x_{2}}{\sqrt{5}\cdot x_{2}}
\end{pmatrix} = \begin{pmatrix}
\frac{-2\cdot x_{2}}{\sqrt{5}\cdot x_{2}}\\ 
\frac{\sqrt{5}}{5}
\end{pmatrix} = \begin{pmatrix}
\frac{-2\sqrt{5}}{5}\\ 
\frac{\sqrt{5}}{5}
\end{pmatrix}$$

для $\lambda_{2} = 3$
$$\begin{pmatrix}
\frac{x_{1}}{\frac{\sqrt{13}}{2}}\\ 
\frac{x_{2}}{\frac{\sqrt{13}}{2}}
\end{pmatrix} = \begin{pmatrix}
\frac{-\frac{3}{2}\cdot x_{2}}{\frac{\sqrt{13}}{2}}\\ 
\frac{2\sqrt{13}}{13}
\end{pmatrix} = \begin{pmatrix}
\frac{-3\sqrt{13}}{13}\\ 
\frac{2\sqrt{13}}{13}
\end{pmatrix}$$

In [1]:
import numpy as np

In [2]:
np.set_printoptions(precision=6, suppress=True)

In [3]:
a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.894427  0.83205 ]
 [ 0.447214 -0.5547  ]]


In [4]:
x_1 = np.array([-2, 1])
x_1 = x_1 / np.linalg.norm(x_1)
x_1

array([-0.894427,  0.447214])

In [5]:
x_2 = np.array([3, -2])
x_2 = x_2 / np.linalg.norm(x_2)
x_2

array([ 0.83205, -0.5547 ])

In [6]:
(-2*np.sqrt(5)/5, np.sqrt(5)/5)

(-0.894427190999916, 0.447213595499958)

In [7]:
(-3*np.sqrt(13)/13, 2*np.sqrt(13)/13)

(-0.8320502943378436, 0.5547001962252291)

__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.

**Решение.**

Запишем выражение $\textbf{A}x=\lambda x$ в общем виде:

$$\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
\lambda
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}$$

И решим его:
$$\begin{cases}
-x_{1} + 0\cdot x_{2} = \lambda\cdot x_{1}, \\
0\cdot x_{1} - x_{2} = \lambda\cdot x_{2}.
\end{cases}$$

Получаем явное решение системы:
$$\begin{cases}
\lambda = -1, \\
\lambda = -1.
\end{cases}$$

Следовательно, для данной матрицы собственным вектором может быть любой, а собственные числа = -1.

In [8]:
b = np.array([[-1, 0], [0, -1]])
w, v = np.linalg.eig(b)
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Собственные значения:
[-1. -1.]
Собственные векторы:
[[1. 0.]
 [0. 1.]]


__3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

**Решение.**

Запишем выражение $\textbf{A}x=\lambda x$:

$$\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}
\begin{pmatrix}
1\\ 
1
\end{pmatrix}=
\lambda
\begin{pmatrix}
1\\ 
1
\end{pmatrix}$$

Решим его:
$$\begin{cases}
1\cdot1 + 1\cdot1 = \lambda\cdot1, \\
-1\cdot1 + 3\cdot1 = \lambda\cdot1.
\end{cases}$$

Получаем явное решение системы:
$$\begin{cases}
\lambda = 2, \\
\lambda = 2.
\end{cases}$$

Следовательно, вектор $x=(1,1)$ является собственным для данной матрицы, собственные числа которой = 2.

In [9]:
c = np.array([[1, 1], [-1, 3]])
w, v = np.linalg.eig(c)
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Собственные значения:
[2. 2.]
Собственные векторы:
[[ 0.707107 -0.707107]
 [ 0.707107 -0.707107]]


**4.** Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix} 0 & 3 & 0\\ 3 & 0 & 0\\ 0 & 0 & 3 \end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

**Решение.**

Запишем выражение $\textbf{A}x=\lambda x$:

$$\begin{pmatrix} 0 & 3 & 0\\ 3 & 0 & 0\\ 0 & 0 & 3 \end{pmatrix}
\begin{pmatrix}
3\\ 
-3\\
-4
\end{pmatrix}=
\lambda
\begin{pmatrix}
3\\ 
-3\\
-4
\end{pmatrix}$$

Решим его:
$$\begin{cases}
0\cdot3 + 3\cdot(-3) + 0\cdot(-4) = \lambda\cdot3, \\
3\cdot3 + 0\cdot(-3) + 0\cdot(-4) = \lambda\cdot(-3), \\
0\cdot3 + 0\cdot(-3) + 3\cdot(-4) = \lambda\cdot(-4).
\end{cases}$$

Получаем:
$$\begin{cases}
3\lambda = -9, \\
-3\lambda = 9, \\
-4\lambda = -12.
\end{cases}$$

Данная система не имеет смысла (нет единственного значения для $\lambda$), следовательно, вектор $x=(3, -3, -4)$ **не** является собственным для данной матрицы (*собственным вектором мог бы быть $x = (3, 3, -4)$ при $\lambda = 3$*).

In [10]:
d = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
w, v = np.linalg.eig(d)
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Собственные значения:
[ 3. -3.  3.]
Собственные векторы:
[[ 0.707107 -0.707107  0.      ]
 [ 0.707107  0.707107  0.      ]
 [ 0.        0.        1.      ]]
