1. Найти с помощью NumPy SVD для матрицы

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$

In [1]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

In [2]:
A = np.array([[1, 2, 0], [0, 0, 5], [3, -4, 2], [1, 6, 5], [0, 1, 0]])
print(f"Матрица А:\n{A}")

U, s, W = np.linalg.svd(A)
V = W.T

D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

print(f"Матрица D:\n{D}")

print(f"Матрица U:\n{U}")
print(f"проверка ортогональности матрицы U: {np.allclose(U @ U.T, np.eye(U.shape[0]))}")

print(f"Матрица V:\n{V}")
print(f"проверка ортогональности матрицы U: {np.allclose(V @ V.T, np.eye(V.shape[0]))}")

print(f"Проверка разложения: {np.allclose(A - U @ D @ V.T, np.zeros((A.shape[0], A.shape[1])))}")

Матрица А:
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]
Матрица D:
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]
Матрица U:
[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]
проверка ортогональности матрицы U: True
Матрица V:
[[ 0.07 -0.37 -0.93]
 [ 0.72  0.67 -0.21]
 [ 0.69 -0.65  0.31]]
проверка ортогональности матрицы U: True
Проверка разложения: True


2. Для матрицы из предыдущего задания найти:

    а) евклидову норму;
    
    б) норму Фробениуса.

__Решение__

а) евклидова норма, как макс. синг. число из матрицы D и с помощью метода norm:

In [3]:
from numpy.linalg import norm

In [4]:
(D[0, 0], norm(A, ord=2))

(8.824868854820444, 8.824868854820444)

б) норма Фробениуса по формуле и с помощью метода norm:

In [5]:
(np.sqrt(sum([D[i, i]**2 for i in range(min(D.shape[0], D.shape[1]))])), norm(A), norm(A, ord='fro'))

(11.045361017187263, 11.045361017187261, 11.045361017187261)